-- MySQL Script generated by MySQL Workbench
-- Mon May 13 13:52:42 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema k3e
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema k3e
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `k3e` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `k3e` ;

-- -----------------------------------------------------
-- Table `k3e`.`province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `k3e`.`province` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `ghn_province_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `k3e`.`district`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `k3e`.`district` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `province_id` INT NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `ghn_district_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `province_id_idx` (`province_id` ASC) VISIBLE,
  CONSTRAINT `fk_district_province`
    FOREIGN KEY (`province_id`)
    REFERENCES `k3e`.`province` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `k3e`.`transporter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `k3e`.`transporter` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(20) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `k3e`.`maincategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `k3e`.`maincategory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `link` VARCHAR(1024) NOT NULL,
  `norder` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `norder_UNIQUE` (`norder` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `k3e`.`subcategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `k3e`.`subcategory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `link` VARCHAR(1024) NOT NULL,
  `maincategory_id` INT NOT NULL,
  `norder` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subcategory_maincategory_idx` (`maincategory_id` ASC) VISIBLE,
  UNIQUE INDEX `norder_UNIQUE` (`norder` ASC) VISIBLE,
  CONSTRAINT `fk_subcategory_maincategory`
    FOREIGN KEY (`maincategory_id`)
    REFERENCES `k3e`.`maincategory` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `k3e`.`imagemap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `k3e`.`imagemap` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `diskpath` VARCHAR(512) NOT NULL,
  `urlpath` VARCHAR(512) NOT NULL,
  `user_id` INT NOT NULL,
  `linked` TINYINT NOT NULL DEFAULT 0,
  `created_time` DATETIME NOT NULL DEFAULT now(),
  `mimetype` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `path_UNIQUE` (`urlpath` ASC) VISIBLE,
  INDEX `fk_imagemap_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_imagemap_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `k3e`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `k3e`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `k3e`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(32) NOT NULL,
  `firstname` VARCHAR(20) NOT NULL,
  `lastname` VARCHAR(32) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `phone` VARCHAR(11) NOT NULL,
  `district_id` INT NULL,
  `locked` INT NOT NULL DEFAULT 0,
  `birthday` DATE NOT NULL,
  `gender` INT NOT NULL,
  `money` DECIMAL(18,3) NOT NULL DEFAULT 0,
  `role` INT NOT NULL DEFAULT 0,
  `avatar_id` BIGINT UNSIGNED NULL,
  `created_time` DATETIME NOT NULL DEFAULT now(),
  `lastaccess_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  INDEX `fk_user_district_idx` (`district_id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `fk_user_imagemap_idx` (`avatar_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_district`
    FOREIGN KEY (`district_id`)
    REFERENCES `k3e`.`district` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_imagemap`
    FOREIGN KEY (`avatar_id`)
    REFERENCES `k3e`.`imagemap` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `k3e`.`shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `k3e`.`shop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL,
  `owner_id` INT NOT NULL,
  `description` VARCHAR(512) NULL,
  `locked` INT NOT NULL,
  `created_time` DATETIME NOT NULL DEFAULT now(),
  `background_id` BIGINT UNSIGNED NULL,
  `avatar_id` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_shop_user_idx` (`owner_id` ASC) VISIBLE,
  UNIQUE INDEX `owner_id_UNIQUE` (`owner_id` ASC) VISIBLE,
  INDEX `fk_logo_idx` (`background_id` ASC) VISIBLE,
  INDEX `fk_avatar_idx` (`avatar_id` ASC) VISIBLE,
  CONSTRAINT `fk_shop_user`
    FOREIGN KEY (`owner_id`)
    REFERENCES `k3e`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wallpaper`
    FOREIGN KEY (`background_id`)
    REFERENCES `k3e`.`imagemap` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avatar`
    FOREIGN KEY (`avatar_id`)
    REFERENCES `k3e`.`imagemap` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `k3e`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `k3e`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `description` TEXT NOT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  `shop_id` INT NOT NULL,
  `original_price` INT UNSIGNED NOT NULL,
  `price` INT UNSIGNED NOT NULL,
  `subcategory_id` INT NOT NULL,
  `weight` INT UNSIGNED NOT NULL,
  `length` INT UNSIGNED NOT NULL,
  `width` INT UNSIGNED NOT NULL,
  `height` INT UNSIGNED NOT NULL,
  `created_time` DATETIME NOT NULL,
  `locked` INT NOT NULL,
  `verified` INT NOT NULL,
  `verified_time` DATETIME NOT NULL,
  `warranty_months_number` VARCHAR(45) NOT NULL,
  `mainimage_id` BIGINT UNSIGNED NOT NULL,
  `views` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_product_subcategory_idx` (`subcategory_id` ASC) VISIBLE,
  INDEX `fk_product_shop_idx` (`shop_id` ASC) VISIBLE,
  UNIQUE INDEX `main_image_id_UNIQUE` (`mainimage_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_subcategory`
    FOREIGN KEY (`subcategory_id`)
    REFERENCES `k3e`.`subcategory` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_shop`
    FOREIGN KEY (`shop_id`)
    REFERENCES `k3e`.`shop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_main_image`
    FOREIGN KEY (`mainimage_id`)
    REFERENCES `k3e`.`imagemap` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `k3e`.`cartitem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `k3e`.`cartitem` (
  `product_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  `created_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`product_id`, `client_id`),
  INDEX `fk_cartitem_product_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_cartitem_user_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_cartitem_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `k3e`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cartitem_user`
    FOREIGN KEY (`client_id`)
    REFERENCES `k3e`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `k3e`.`productimage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `k3e`.`productimage` (
  `product_id` INT NOT NULL,
  `norder` INT UNSIGNED NOT NULL,
  `imagemap_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`product_id`, `norder`),
  UNIQUE INDEX `image_id_UNIQUE` (`imagemap_id` ASC) VISIBLE,
  CONSTRAINT `fk_productimage_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `k3e`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_productimage_imagemap`
    FOREIGN KEY (`imagemap_id`)
    REFERENCES `k3e`.`imagemap` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `k3e`.`productattribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `k3e`.`productattribute` (
  `product_id` INT NOT NULL,
  `norder` INT UNSIGNED NOT NULL,
  `attributename` VARCHAR(100) NOT NULL,
  `attributevalue` VARCHAR(1024) NOT NULL,
  INDEX `fk_productattribute_product_idx` (`product_id` ASC) VISIBLE,
  PRIMARY KEY (`norder`, `product_id`),
  CONSTRAINT `fk_productattribute_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `k3e`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `k3e`.`ward`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `k3e`.`ward` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(20) NOT NULL,
  `district_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `ghn_ward_code` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ward_district_idx` (`district_id` ASC) VISIBLE,
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE,
  CONSTRAINT `fk_ward_district`
    FOREIGN KEY (`district_id`)
    REFERENCES `k3e`.`district` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `k3e`.`deliveryaddress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `k3e`.`deliveryaddress` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(32) NOT NULL,
  `firstname` VARCHAR(20) NOT NULL,
  `user_id` INT NOT NULL,
  `def` INT NOT NULL,
  `address` VARCHAR(200) NOT NULL,
  `ward_id` INT NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `created` DATETIME NOT NULL DEFAULT now(),
  INDEX `fk_deliveryaddress_user_idx` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_deliveryaddress_ward_idx` (`ward_id` ASC) VISIBLE,
  CONSTRAINT `fk_deliveryaddress_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `k3e`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_deliveryaddress_ward`
    FOREIGN KEY (`ward_id`)
    REFERENCES `k3e`.`ward` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `k3e`.`paymenttype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `k3e`.`paymenttype` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(20) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `k3e`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `k3e`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ordercode` VARCHAR(20) NOT NULL,
  `shop_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `status` INT NOT NULL,
  `note` VARCHAR(1024) NULL,
  `created_time` DATETIME NOT NULL DEFAULT now(),
  `total_price` INT NOT NULL,
  `ship_fee` INT UNSIGNED NOT NULL,
  `paid` INT NOT NULL,
  `paycomplete` INT NOT NULL,
  `clientname` VARCHAR(52) NOT NULL,
  `clientphone` VARCHAR(11) NOT NULL,
  `clientaddress` VARCHAR(200) NOT NULL,
  `clientwardname` VARCHAR(100) NOT NULL,
  `clientdistrictname` VARCHAR(200) NOT NULL,
  `clientprovincename` VARCHAR(200) NOT NULL,
  `shopname` VARCHAR(52) NOT NULL,
  `shopphone` VARCHAR(11) NOT NULL,
  `shopaddress` VARCHAR(200) NOT NULL,
  `shopwardname` VARCHAR(100) NOT NULL,
  `shopdistrictname` VARCHAR(200) NOT NULL,
  `shopprovincename` VARCHAR(200) NOT NULL,
  `weight` INT NOT NULL,
  `length` INT NOT NULL,
  `width` INT NOT NULL,
  `height` INT NOT NULL,
  `paymenttype_id` INT NOT NULL,
  `transporter_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_user_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_order_shop_idx` (`shop_id` ASC) VISIBLE,
  INDEX `fk_order_transporter_idx` (`transporter_id` ASC) VISIBLE,
  INDEX `fk_order_paymenttype_idx` (`paymenttype_id` ASC) VISIBLE,
  UNIQUE INDEX `ordercode_UNIQUE` (`ordercode` ASC) VISIBLE,
  CONSTRAINT `fk_order_shop`
    FOREIGN KEY (`shop_id`)
    REFERENCES `k3e`.`shop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_user`
    FOREIGN KEY (`client_id`)
    REFERENCES `k3e`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_transporter`
    FOREIGN KEY (`transporter_id`)
    REFERENCES `k3e`.`transporter` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_paymenttype`
    FOREIGN KEY (`paymenttype_id`)
    REFERENCES `k3e`.`paymenttype` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `k3e`.`assessment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `k3e`.`assessment` (
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `comment` TEXT NOT NULL,
  `starpoint` INT UNSIGNED NOT NULL,
  `created_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`order_id`, `product_id`),
  INDEX `fk_assessment_user_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_assessment_order_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_assessment_product_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_assessment_user`
    FOREIGN KEY (`client_id`)
    REFERENCES `k3e`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_assessment_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `k3e`.`order` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_assessment_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `k3e`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `k3e`.`orderitem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `k3e`.`orderitem` (
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  `price` INT UNSIGNED NOT NULL,
  `warranty_months_number` INT NOT NULL,
  PRIMARY KEY (`order_id`, `product_id`),
  INDEX `fk_orderitem_product_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_orderitem_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `k3e`.`order` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orderitem_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `k3e`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `k3e`.`onepayorder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `k3e`.`onepayorder` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `orderinfo` VARCHAR(32) NOT NULL,
  `transactionref` VARCHAR(34) NOT NULL,
  `currencycode` VARCHAR(3) NOT NULL DEFAULT 'VND',
  `amount` VARCHAR(21) NOT NULL,
  `transactionno` VARCHAR(12) NULL,
  `transactioncode` VARCHAR(5) NULL,
  `transactionmessage` VARCHAR(255) NULL,
  `additiondata` VARCHAR(6) NULL,
  `merchant` VARCHAR(12) NOT NULL,
  `accesscode` VARCHAR(8) NOT NULL,
  `ticketno` VARCHAR(15) NOT NULL,
  `created_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  INDEX `fk_onepayorder_order_idx` (`order_id` ASC) VISIBLE,
  UNIQUE INDEX `transactionref_UNIQUE` (`transactionref` ASC) VISIBLE,
  CONSTRAINT `fk_onepayorder_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `k3e`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `k3e`.`orderlog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `k3e`.`orderlog` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `order_status` INT NOT NULL,
  `content` VARCHAR(512) NOT NULL,
  `created_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  INDEX `fk_orderlog_order_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_orderlog_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `k3e`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `k3e`.`ghntransporter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `k3e`.`ghntransporter` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `orderid` INT NULL,
  `ordercode` VARCHAR(50) NULL,
  `currentstatus` VARCHAR(200) NULL,
  `extrafee` INT NULL,
  `totalservicefee` INT NULL,
  `expecteddeliverytime` DATETIME NULL,
  `note` VARCHAR(1024) NULL,
  `serviceid` INT NULL,
  `servicename` VARCHAR(45) NULL,
  `insurancefee` INT NULL,
  `codamount` INT NOT NULL,
  `fromdistrictid` INT NOT NULL,
  `fromwardcode` VARCHAR(50) NULL,
  `todistrictid` INT NOT NULL,
  `towardcode` VARCHAR(45) NULL,
  `paymenttypeid` INT NULL,
  `clienthubid` INT NULL,
  `sortcode` VARCHAR(200) NULL,
  `created_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  INDEX `fk_ghntransporter_order_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_ghntransporter_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `k3e`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `k3e`.`productviewslog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `k3e`.`productviewslog` (
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `views` INT NOT NULL,
  `created_time` DATETIME NOT NULL DEFAULT now(),
  `latest_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`user_id`, `product_id`),
  INDEX `fk_productviewslog_product_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_productviewslog_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `k3e`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productviewslog_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `k3e`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
